before_install:
  - yes | sudo add-apt-repository ppa:cmrx64/cargo
  - yes | sudo add-apt-repository ppa:hansjorg/rust
  - sudo apt-get update

install:
  - sudo apt-get install cargo rust-nightly libopenblas-dev

script:
  - rustc --version
  - make
  - make test

branches:
  only: master
