env:
  global:
    - URL=https://www.dropbox.com/sh/hz03qag74f3p6ol/AABGxiO934a6y9ZCULI0zBwXa/rust-2015-06-18-a9eda99-x86_64-unknown-linux-gnu-88034602459af55b250836da861a133815222fa8.tar.gz
    - secure: B/kcbcUvqUkSXNcbfjA8AQgC57IgWIGd8jgjysAuJUbv02e0PjyGK864NCIMn+UeUwhdni8F73EtEkJS6fiJ69BO7sVQzgN47ePG5nPnzgXieOcyLABtUsozZfB2Jy7HPbXCBN313wohmGvDwRPf0w4vszfmryfgCXe9haXGGFc=

before_install:
  # This PPA has a newer version of OpenBLAS
  - sudo add-apt-repository ppa:staticfloat/julia-deps -y
  - sudo apt-get update

install:
  - sudo apt-get install libopenblas-dev liblapack-dev
  - source install.sh

script:
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/openblas-base;
  - src/nn/fetch_data.sh
  - cargo run --release --verbose
  - cargo doc --verbose

after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && bash upload-docs.sh'

branches:
  only: ng

notifications:
  email:
    on_success: never
