language: rust

env:
  global:
    - secure: B/kcbcUvqUkSXNcbfjA8AQgC57IgWIGd8jgjysAuJUbv02e0PjyGK864NCIMn+UeUwhdni8F73EtEkJS6fiJ69BO7sVQzgN47ePG5nPnzgXieOcyLABtUsozZfB2Jy7HPbXCBN313wohmGvDwRPf0w4vszfmryfgCXe9haXGGFc=
  matrix:
    # FIXME (#12) Reenable OpenBLAS testing
    #- BLAS=OpenBLAS
    - BLAS=reference

before_install:
  # This PPA has a newer version of OpenBLAS
  - if [[ $BLAS == 'OpenBLAS' ]]; then
      sudo add-apt-repository ppa:staticfloat/julia-deps -y;
    fi
  - sudo apt-get update

install:
  - if [[ $BLAS == 'OpenBLAS' ]]; then
      sudo apt-get install libopenblas-dev;
    else
      sudo apt-get install libblas-dev;
    fi

script:
  # Not sure why travis needs this, without it linking to libopenblas.so.0 fails
  - if [[ $BLAS == 'OpenBLAS' ]]; then
      export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/openblas-base;
    fi
  - cargo build --features macros --verbose
  - cargo test --features macros --verbose
  - cargo doc --features macros --verbose
  - ./check-line-length.sh

after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && bash upload-docs.sh'

branches:
  only: master
