language: rust

env:
  global:
    - secure: D/SGyr/TJwlfNpPgKp6oOWcy2ED9ylt+rznLJF24Sb7YqJ5V0xjYTGbvOcvzqntKzU971v8IUS+fT8E1u1eDQHzmY1GxjnPsKklhW+RxujbKqy1FALM3mdd9sf1qtHXk/55irlPumYuO9C7wgSqinm1f3yF00J2EDbkNLVUPlBY=
  matrix:
    - BLAS=OpenBLAS
    - BLAS=reference

before_install:
  # This PPA has a newer version of OpenBLAS
  - if [[ $BLAS == 'OpenBLAS' ]]; then
      sudo add-apt-repository ppa:staticfloat/julia-deps -y;
    fi
  - sudo apt-get update

install:
  - if [[ $BLAS == 'OpenBLAS' ]]; then
      sudo apt-get install libopenblas-dev;
    else
      sudo apt-get install libblas-dev;
    fi

script:
  # Not sure why travis needs this, without it linking to libopenblas.so.0 fails
  - if [[ $BLAS == 'OpenBLAS' ]]; then
      export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/openblas-base;
    fi
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc --verbose && mv target/doc doc
  - ./check-line-length.sh

after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh'

branches:
  only: master
