env:
  global:
    - URL=https://www.dropbox.com/sh/hz03qag74f3p6ol/AADOLQA-i0W6P-6M6Lt345aMa/rust-2015-07-01-9d270f0-x86_64-unknown-linux-gnu-c183fa37e1c48386841d84c5460b59e3afd85f49.tar.gz
    - secure: B/kcbcUvqUkSXNcbfjA8AQgC57IgWIGd8jgjysAuJUbv02e0PjyGK864NCIMn+UeUwhdni8F73EtEkJS6fiJ69BO7sVQzgN47ePG5nPnzgXieOcyLABtUsozZfB2Jy7HPbXCBN313wohmGvDwRPf0w4vszfmryfgCXe9haXGGFc=

before_install:
  # This PPA has a newer version of OpenBLAS
  - sudo add-apt-repository ppa:staticfloat/julia-deps -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update

install:
  - sudo apt-get install libopenblas-dev liblapack-dev
  - sudo apt-get install libstdc++6
  - source install.sh

script:
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/openblas-base;
  - src/nn/fetch_data.sh
  - cargo run --release --verbose
  - cargo doc --verbose

after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && bash upload-docs.sh'

branches:
  only: ng

notifications:
  email:
    on_success: never
