[package]
name = "linalg"
version = "0.0.1"
authors = ["Jorge Aparicio <japaric@linux.com>"]

[[lib]]
name = "linalg"
path = "src/lib.rs"

[dependencies.quickcheck]

git = "https://github.com/BurntSushi/quickcheck"
