[package]

name = "linalg"
version = "0.0.0"
authors = ["Jorge Aparicio <japaric@linux.com>"]

[dependencies.linalg_macros]
path = "macros"

[dependencies.num]
git = "https://github.com/rust-lang/num"

[dev-dependencies.quickcheck]
git = "https://github.com/BurntSushi/quickcheck"

[dev-dependencies.quickcheck_macros]
git = "https://github.com/BurntSushi/quickcheck"
