[package]

name = "linalg"
version = "0.0.0"
authors = ["Jorge Aparicio <japaricious@gmail.com>"]

[features]
macros = ["linalg_macros"]

[dependencies]
rand = "*"

[dependencies.complex]
git = "https://github.com/japaric/complex.rs"

[dependencies.onezero]
git = "https://github.com/japaric/onezero.rs"

[dependencies.linalg_macros]
optional = true
path = "macros"

[dev-dependencies.quickcheck]
git = "https://github.com/burntsushi/quickcheck"

[dev-dependencies.quickcheck_macros]
git = "https://github.com/burntsushi/quickcheck"
